
# https://coreos.com/etcd/docs/latest/op-guide/container.html#docker
# export NODE1=192.168.1.21
#
# docker run \
#   -p 2379:2379 \
#   -p 2380:2380 \
#   --volume=${DATA_DIR}:/etcd-data \
#   --name etcd quay.io/coreos/etcd:latest \
#   /usr/local/bin/etcd \
#   --data-dir=/etcd-data --name node1 \
#   --initial-advertise-peer-urls http://${NODE1}:2380 --listen-peer-urls http://${NODE1}:2380 \
#   --advertise-client-urls http://${NODE1}:2379 --listen-client-urls http://${NODE1}:2379 \
#   --initial-cluster node1=http://${NODE1}:2380
#
# etcdctl --endpoints=http://${NODE1}:2379 member list

version: '2'

services:
  mysql:
    environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_USER=testuser
    - MYSQL_PASSWORD=testpassword
    - MYSQL_DATABASE=testdb
    image: mysql:5.7
    restart: unless-stopped
    volumes:
    - /srv/mysql/data:/var/lib/mysql

  php-nginx:
    environment:
    - MYSQL_USER=testuser
    - MYSQL_PASSWORD=testpassword
    - MYSQL_DATABASE=testdb
    - MYSQL_SERVER_ADDRESS=mysql:3306
    - DOCKER_RESOURCE_PROVIDER=go-to-docker:10052
    image: tangfeixiong/nginx-php-demo
    ports:
    - "80:80"
    restart: on-failure    

  isc-flag:
    environment:
    - SPRING_DATASOURCE_URL='jdbc:mysql://mysql:3306/testdb'
    - SPRING_DATASOURCE_USERNAME='testuser'
    - SPRING_DATASOURCE_PASSWORD='testpassword' 
    - SERVER_PORT='8082'
    image: 172.17.4.50:5000/isc-flag
    ports:
    - "8082:8082"
    restart: always    

  go-to-docker:
    depends_on:
    - etcd
    environment:
    - DOCKER_CONFIG_JSON='{"auths":{}}'
    - REGISTRY_CERTS_JSON='{}'
    image: docker.io/tangfeixiong/go-to-docker:0.1
    # ports:
    # - "10052:10052"
    privileged: true
    restart: always
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro

  etcd:
    command: 
    - /usr/local/bin/etcd
    - --data-dir=/etcd-data
    - --name
    - node1
    - --initial-advertise-peer-urls
    - http://172.17.4.50:2380
    - --listen-peer-urls
    - http://172.17.4.50:2380
    - --advertise-client-urls
    - http://172.17.4.50:2379
    - --listen-client-urls 
    - http://172.17.4.50:2379
    - --initial-cluster 
    - node1=http://172.17.4.50:2380
    image: quay.io/coreos/etcd:v3.2.4
    ports:
    - "2379:2379"
    - "2380:2380"
    restart: always
    volumes:
    - /srv/etcd/data:/etcd-data

